[custom.all.postgres]
type = "local"
path = "."
ipkg = "postgres.ipkg"
test = "test/test.ipkg"

[custom.all.postgres-test]
type = "local"
path = "test"
ipkg = "test.ipkg"
[custom.all.runtime]
type = "local"
path = "../runtime"
ipkg = "runtime.ipkg"

[custom.all.postgres-async]
type = "local"
path = "async"
ipkg = "postgres-async.ipkg"
