[custom.all.postgres]
type = "local"
path = "."
ipkg = "postgres.ipkg"
test = "test/test.ipkg"

[custom.all.postgres-test]
type = "local"
path = "test"
ipkg = "test.ipkg"
[custom.all.flux-async]
type = "local"
path = "../idris2-flux-async"
ipkg = "flux-async.ipkg"

[custom.all.postgres-async]
type = "local"
path = "async"
ipkg = "postgres-async.ipkg"
